# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: theme_leaf_lab_v2
  font: font_leaf_lab
  font_size: S

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'LEAF Lab, within the University of Toronto Institute for Aerospace Science'
    description: 'The website of the Learning, Embodied Autonomy, and Forecasting (LEAF) research laboratory.'
    twitter: 'nick_rhinehart'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    show_day_night: false
    show_search: true
    highlight_active_link: true  

# 
i_am_a_sponsor: true
power_ups:
  hide_published_with: true
# Site footer

footer:
  block: minimal
  copyright:
    notice: '
    <div class="universal-wrapper">
    <hr style="width: 100%; background: 1px solid #1E3765"></hr>
    <div class="row" style="display: flex; justify-content: center; flex-direction: row; column-gap: 1vw">
      <a href="#"><img src="/images/logo.png" alt="LEAF Lab logo" style="height: 80px; width:auto"></a>
      <div style="border-left: 1px solid #1E3765; height: 40px; margin-top: 20px; margin-bottom: 20px"></div>
      <a href="https://robotics.utoronto.ca" target="_blank"><img src="/images/ri-logo.png" style="height: 80px; width:auto" alt="U of T Robotics Institute Logo"></a>
      <div style="border-left: 1px solid #1E3765; height: 40px; margin-top: 20px; margin-bottom: 20px"></div>
      <a href="https://utoronto.ca" target="_blank"><img src="/images/uot-logo.png" style="height: 80px; width:auto" alt="U of T Logo"></a>
    </div>
    <br><br>
    <div class="row"><div class="col-lg-12"><h3 style="text-align:left;">Statement of Land Acknowledgement</h3>
    <p style="text-align: left;">We wish to acknowledge this land on which the University of Toronto operates. For thousands of years it has been the traditional land of the Huron-Wendat, the Seneca, and the Mississaugas of the Credit. Today, this meeting place is still the home to many Indigenous people from across Turtle Island and we are grateful to have the opportunity to work on this land.
      <br><a href="https://indigenous.utoronto.ca/about/land-acknowledgement/">Read more about this Statement of Land Acknowledgement.</a>
    </p><br>
    <p style="text-align: left">© {year} Nick Rhinehart.</p></div></div></div>'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: mla
